import { DashboardIcon, Pencil1Icon } from "@radix-ui/react-icons";
import {
  Activity,
  Banknote,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarOff,
  ClipboardList,
  Clock,
  Coins,
  FileText,
  Folder,
  Globe2,
  GraduationCap,
  HelpCircle,
  Image,
  Languages,
  Layers,
  Lock,
  Mail,
  MapPin,
  MessageSquare,
  Plus,
  Send,
  Settings,
  Share2,
  Shield,
  Star,
  Store,
  Tag,
  Ticket,
  Truck,
  User,
  UserCheck,
  Users
} from "lucide-react";
import { IoContract } from "react-icons/io5";

export const mainIcons = {
  users: User,
  edit: Pencil1Icon,
  create: Plus,
  Dashboard: DashboardIcon,
  dashboard: DashboardIcon,
  languages: Languages,
  currency: Coins,
  banners: Image,
  cities: Building,
  transactions: Banknote,
  stores: Store,
  category: Folder,
  categories: Folder,
  subCategories: Layers,
  branches: MapPin,
  rating: Star,
  banks: Banknote,
  locations: MapPin,
  accounting: Banknote,
  modules: Settings,
  fund: Banknote,
  schedule: Clock,
  delivery: Truck,
  "users & access": User,
  content: Folder,
  withdraw: Banknote,
  "orders & support": ClipboardList,
  roles: Shield,
  permissions: Lock,
  orders: ClipboardList,
  complaint: MessageSquare,
  services: Settings,
  zones: MapPin,
  coupons: Ticket,
  customers: Briefcase,
  Customers: Briefcase,
  blog: FileText,
  Blog: FileText,
  faq: HelpCircle,
  Faq: HelpCircle,
  contactUs: Mail,
  ContactUs: Mail,
  sentEmails: Send,
  SentEmails: Send,
  visitors: Globe2,
  Visitors: Globe2,
  socialMedia: Share2,
  academicContent: GraduationCap,
  systemSettings: Settings,
  settings: Settings,
  // HR-specific
  hr: Briefcase,
  contractTypes: FileText,
  leaveTypes: CalendarOff,
  sections: Building2,
  salaries: Coins,
  Contract: IoContract,
  contract: IoContract,
  shifts: Clock,
  deductions: Coins,
  officialHolidays: Calendar,
  attendance: UserCheck,
  calculator: Calculator,
  employees: Users,
  leaveRequests: CalendarOff,
  announcements: MessageSquare,
  warnings: Shield,
  performanceReviews: Star,
  trainingPrograms: GraduationCap,
  assets: Folder,
  expenses: Coins,
  employeeDocuments: FileText,
  onboardingTemplates: ClipboardList,
  onboardingTasks: UserCheck
};

export const columnsIcons = {
  id: Tag,
  name: User,
  user: User,
  title: FileText,
  notes: FileText,
  priority: Activity,
  date: Calendar,
  overall_rating: Star,
  category: Folder,
  status: Activity,
  address: MapPin,
  work: Briefcase,
  symbol: Coins,
  created_at: Calendar,
  phone: Activity,
  is_basic: FileText,
  is_paid: Banknote,
  from: Clock,
  to: Clock,
  rest: Clock,
  day: Calendar,
  bonus_day_off: Plus,
  has_attendance: UserCheck,
  has_annual_leave: CalendarOff,
  from_date: Calendar,
  to_date: Calendar,
  description: FileText,
  Employee: User,
  Section: Building2,
  Contract: IoContract,
  Amount: Coins,
  Phone: Activity,
  Date: Calendar,
  Status: Activity,
  "Languages Information": Languages,
  createdAt: Calendar
};

export type MainIconsType = keyof typeof mainIcons;
export type ColumnsIconsType = keyof typeof columnsIcons;
export type AllIconsType = MainIconsType | ColumnsIconsType;
